### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by kells64000** [yoanbernabeu/Symfony-And-Docker-Makefile-Taskfile#1]
Bonjour Yoan,

Voici un exemple de makefile que j'utilise dans mes projets sf => https://gitlab.com/samples-code-projects/php/symfony/-/blob/master/Makefile

Pour chainer les tâches j'utilise la syntaxe suivante :

install: ## Install and start the project
install: build start vendor db

Pour éviter d'écrire autant de tâches qu'il existe de commandes symfony j'utilise la syntaxe suivante : 

sf: ## List Symfony commands   
	$(CONSOLE) $(command)

Grâce à cette syntaxe je peux lister les commandes sf en faisant : make sf
Et cela me permet de jouer les commandes de cette manière : make sf command="clear:cache"

Si cela t'intéresse il y a une super vidéo de Romain Gautier qui présente sa manière de voir le makefile => https://www.youtube.com/watch?v=_OEDoPMvNY4

**Comment by yoanbernabeu** [comment]
Merci @kells64000 je t'ai piqué une idée !
